# ROS2 Parameters for Scorecard Submission System.

# Shared robot list - referenced in each node's parameters
# Valid robot names: dione (UAV), deimos, phobos, titania, oberon (UGVs)

system_location_submission:
  ros__parameters:
    start_run: false
    system_location_rate: 4
    threshold_path: "/home/dtc/ws/src/scorecard_submitter/config/threshold_config.json"
    data_path: "/home/dtc/data"
    robot_names: ["dione", "deimos", "phobos", "titania", "oberon"]

gate1_node:
  ros__parameters:
    robot_names: ["dione", "deimos", "phobos", "titania", "oberon"]

gate2_node:
  ros__parameters:
    robot_names: ["dione", "deimos", "phobos", "titania", "oberon"]

gate3_node:
  ros__parameters:
    robot_names: ["dione", "deimos", "phobos", "titania", "oberon"]

gate4_node:
  ros__parameters:
    robot_names: ["dione", "deimos", "phobos", "titania", "oberon"]

hmt_node:
  ros__parameters:
    robot_names: ["dione", "deimos", "phobos", "titania ", "oberon"]