FROM dtcpronto/ros-jazzy:full

# -----------------------------------------------------
# User setup
# -----------------------------------------------------

USER root

# -----------------------------------------------------
# Additional ROS + Python packages not already in base
# -----------------------------------------------------
RUN apt-get update && apt-get install -y \
    ros-jazzy-rosbag2-storage-mcap \
    ros-jazzy-vision-opencv \
    ros-jazzy-vision-msgs \
    ros-jazzy-cv-bridge \
    python3-utm \
    python3-flask \
    python3-folium \
    python3-flask-socketio \
    python3-scipy \
    python3-dotenv \
    python3-requests \
 && rm -rf /var/lib/apt/lists/*

# -----------------------------------------------------
# Environment setup
# -----------------------------------------------------
USER dtc
WORKDIR /home/dtc

RUN mkdir -p /home/dtc/ws/src

COPY --chown=dtc:dtc ./entrypoint.bash /home/dtc/entrypoint.bash
RUN chmod +x /home/dtc/entrypoint.bash

ENV MOCHA=false \
    RTK=false \
    SENDER=false \
    VIZ=false

RUN echo ". /opt/ros/jazzy/setup.bash" >> /home/dtc/.bashrc \
 && echo "source /home/dtc/ws/install/setup.bash" >> /home/dtc/.bashrc \
 && echo 'export PS1="\[$(tput setaf 2; tput bold)\]\u\[$(tput setaf 7)\]@\[$(tput setaf 3)\]\h\[$(tput setaf 7)\]:\[$(tput setaf 4)\]\W\[$(tput setaf 7)\]$ \[$(tput sgr0)\]"' >> /home/dtc/.bashrc

ENTRYPOINT ["/home/dtc/entrypoint.bash"]